services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: planner
      POSTGRES_PASSWORD: plannerpw
      POSTGRES_DB: plannerdb
    ports:
      - "5432:5432"

    volumes:
      - pg_data:/var/lib/postgresql/data
    
volumes:
    pg_data: